export const projects = [
  {
    id: 1,
    category: "commercial",
    nameFA: "ساختمان مرکزی بویلر مپنا",
    nameEN: "MAPNA Boiler Central Building",
    locationFA: "تهران - میرداماد",
    locationEN: "Tehran - Mirdamad",
    image: "/projects/mapna.jpg",
  },
  {
    id: 2,
    category: "commercial",
    nameFA: "ساختمان دادگستری مشهد",
    nameEN: "Mashhad Judiciary Building",
    locationFA: "مشهد",
    locationEN: "Mashhad",
    image: "/projects/judiciary.jpg",
  },
  {
    id: 3,
    category: "commercial",
    nameFA: "برج وزارت کشور",
    nameEN: "Ministry of Interior Tower",
    locationFA: "تهران",
    locationEN: "Tehran",
    image: "/projects/interior.jpg",
  },
  {
    id: 4,
    category: "commercial",
    nameFA: "مرکز خرید البرز",
    nameEN: "Alborz Shopping Center",
    locationFA: "کرج",
    locationEN: "Karaj",
    image: "/projects/alborz.jpg",
  },
  {
    id: 5,
    category: "industrial",
    nameFA: "ذوب‌آهن اصفهان",
    nameEN: "Isfahan Steel Company",
    locationFA: "اصفهان",
    locationEN: "Isfahan",
    image: "/projects/steel.jpg",
  },
  {
    id: 6,
    category: "industrial",
    nameFA: "پالایشگاه آبادان",
    nameEN: "Abadan Refinery",
    locationFA: "آبادان",
    locationEN: "Abadan",
    image: "/projects/refinery.jpg",
  },
  {
    id: 7,
    category: "industrial",
    nameFA: "پتروشیمی مبین عسلویه",
    nameEN: "Mobin Petrochemical Complex",
    locationFA: "عسلویه",
    locationEN: "Assaluyeh",
    image: "/projects/petrochemical.jpg",
  },
  {
    id: 8,
    category: "healthcare",
    nameFA: "بیمارستان ولیعصر تهران",
    nameEN: "Valiasr Hospital Tehran",
    locationFA: "تهران",
    locationEN: "Tehran",
    image: "/projects/valiasr.jpg",
  },
  {
    id: 9,
    category: "healthcare",
    nameFA: "بیمارستان امام خمینی اهواز",
    nameEN: "Imam Khomeini Hospital Ahvaz",
    locationFA: "اهواز",
    locationEN: "Ahvaz",
    image: "/projects/imam.jpg",
  },
  {
    id: 10,
    category: "hospitality",
    nameFA: "هتل فرودگاهی اکسیس",
    nameEN: "Axis Airport Hotel",
    locationFA: "فرودگاه امام خمینی",
    locationEN: "Imam Khomeini Airport",
    image: "/projects/axis.jpg",
  },
  {
    id: 11,
    category: "hospitality",
    nameFA: "هتل ارم شیراز",
    nameEN: "Eram Hotel Shiraz",
    locationFA: "شیراز",
    locationEN: "Shiraz",
    image: "/projects/eram.jpg",
  },
  {
    id: 12,
    category: "educational",
    nameFA: "دانشگاه علوم پزشکی بقیةالله",
    nameEN: "Baqiyatallah University of Medical Sciences",
    locationFA: "تهران",
    locationEN: "Tehran",
    image: "/projects/baqiyatallah.jpg",
  },
  {
    id: 13,
    category: "educational",
    nameFA: "دانشگاه صنعتی اراک",
    nameEN: "Arak University of Technology",
    locationFA: "اراک",
    locationEN: "Arak",
    image: "/projects/arak.jpg",
  },
  {
    id: 14,
    category: "residential",
    nameFA: "مجتمع مسکونی پارسیان",
    nameEN: "Parsian Residential Complex",
    locationFA: "تهران",
    locationEN: "Tehran",
    image: "/projects/parsian.jpg",
  },
  {
    id: 15,
    category: "commercial",
    nameFA: "سینما آزادی",
    nameEN: "Azadi Cinema Complex",
    locationFA: "تهران",
    locationEN: "Tehran",
    image: "/projects/azadi.jpg",
  },
]

export const partners = [
  {
    name: "Blue Star",
    country: "India",
    countryFA: "هند",
    logo: "/partners/bluestar.png",
    description: "Largest HVAC manufacturer in India",
    descriptionFA: "بزرگترین تولیدکننده تهویه مطبوع در هند",
  },
  {
    name: "Thermax",
    country: "India",
    countryFA: "هند",
    logo: "/partners/thermax.png",
    description: "Absorption chillers specialist",
    descriptionFA: "متخصص چیلرهای جذبی",
  },
  {
    name: "Vicot",
    country: "China",
    countryFA: "چین",
    logo: "/partners/vicot.png",
    description: "Comprehensive HVAC solutions",
    descriptionFA: "راهکارهای جامع تهویه مطبوع",
  },
  {
    name: "Engie",
    country: "Germany",
    countryFA: "آلمان",
    logo: "/partners/engie.png",
    description: "Magnetic Turbocor chillers",
    descriptionFA: "چیلرهای مغناطیسی توربوکور",
  },
  {
    name: "K-FLEX",
    country: "Italy",
    countryFA: "ایتالیا",
    logo: "/partners/kflex.png",
    description: "Elastomeric insulation",
    descriptionFA: "عایق‌های الاستومری",
  },
]

export const certifications = [
  {
    name: "ISO 9001",
    nameFA: "ISO 9001",
    description: "Quality Management System",
    descriptionFA: "سیستم مدیریت کیفیت",
    issuer: "TUV Germany",
    issuerFA: "TUV آلمان",
  },
  {
    name: "ISO 14001",
    nameFA: "ISO 14001",
    description: "Environmental Management System",
    descriptionFA: "سیستم مدیریت زیست‌محیطی",
    issuer: "TUV Germany",
    issuerFA: "TUV آلمان",
  },
  {
    name: "LEED",
    nameFA: "LEED",
    description: "Leadership in Energy and Environmental Design",
    descriptionFA: "استاندارد ساختمان سبز آمریکا",
    issuer: "US Green Building Council",
    issuerFA: "شورای ساختمان سبز آمریکا",
  },
  {
    name: "CEM",
    nameFA: "CEM",
    description: "Certified Energy Manager",
    descriptionFA: "مدیریت انرژی حرفه‌ای",
    issuer: "AEE",
    issuerFA: "انجمن مهندسین انرژی",
  },
]

export const stats = [
  {
    valueFA: "+۷۰۰",
    valueEN: "700+",
    labelFA: "پروژه موفق",
    labelEN: "Successful Projects",
  },
  {
    valueFA: "+۳۵",
    valueEN: "35+",
    labelFA: "بیمارستان",
    labelEN: "Hospitals",
  },
  {
    valueFA: "+۵۰",
    valueEN: "50+",
    labelFA: "مجموعه ورزشی",
    labelEN: "Sports Complexes",
  },
  {
    valueFA: "+۱۰M",
    valueEN: "10M+",
    labelFA: "متر مربع مسکونی",
    labelEN: "Sqm Residential",
  },
]

export const services = [
  {
    icon: "Snowflake",
    titleFA: "چیلرهای صنعتی",
    titleEN: "Industrial Chillers",
    descFA: "انواع چیلرهای تراکمی و جذبی با تکنولوژی روز",
    descEN: "Various compression and absorption chillers with modern technology",
  },
  {
    icon: "Wind",
    titleFA: "هواساز و تهویه",
    titleEN: "AHU & Ventilation",
    descFA: "طراحی و اجرای سیستم‌های هواساز و تهویه صنعتی",
    descEN: "Design and implementation of air handling and industrial ventilation systems",
  },
  {
    icon: "Thermometer",
    titleFA: "سیستم‌های حرارتی",
    titleEN: "Heating Systems",
    descFA: "راهکارهای گرمایشی بهینه و کم‌مصرف",
    descEN: "Optimal and energy-efficient heating solutions",
  },
  {
    icon: "Droplets",
    titleFA: "تصفیه آب",
    titleEN: "Water Treatment",
    descFA: "سیستم‌های تصفیه آب و فاضلاب صنعتی",
    descEN: "Industrial water and wastewater treatment systems",
  },
  {
    icon: "Zap",
    titleFA: "مدیریت انرژی",
    titleEN: "Energy Management",
    descFA: "ذخیره‌سازی سرما، بازیافت حرارت و CCHP",
    descEN: "Ice bank, heat recovery, and CCHP systems",
  },
  {
    icon: "Wrench",
    titleFA: "خدمات پس از فروش",
    titleEN: "After-Sales Service",
    descFA: "پشتیبانی و نگهداری تجهیزات تهویه مطبوع",
    descEN: "HVAC equipment support and maintenance",
  },
]
